### ISSUE TITLE
Bwuno ne peut pas rejoindre plus de serveurs discord

### ISSUE THREAD

**Issue by Xya3l** [Paul-Marie/Bwuno#1]
![Screenshot_2023-02-14-12-40-39-02_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/125364699/218727793-419f9f12-c55b-4fa6-a2a3-8ad73a77bb70.jpg)

**Comment by Paul-Marie** [comment]
Bonjour, c'est un problème lié à Discord car Bwuno doit valider sa certification d'intents.

Le bot étant certifié, Discord devrais vite le valider.

Je reviendrais vers toi des qu'ils m'auront confirmé que le problème est résolu !

**Comment by Paul-Marie** [comment]
@Xya3l All right ! c'est réglé :)

**Comment by Xya3l** [comment]
Merci. Nickel. problème réglé.
